### ISSUE TITLE
Is there any way to install this package manually?

### ISSUE THREAD

**Issue by collegeimprovements** [rgbkrk/atom-script#1062]
We use atom behind the proxy. Currently we get this error because of firewall.
Is there any way to manually install this package?

``` javascript
Installing “script@3.9.0” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\username\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\username\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\username\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\username\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\username\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\username\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\username\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\username\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-5a71a541: github.com[0: 192.30.253.113]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\username\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\username\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\username\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\username\\.atom\\.apmrc" "install" "C:\\Users\\username\\AppData\\Local\\Temp\\d-116730-2188-bgvll2\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\username\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issue
```

Thanks for making this wonderful plugin.

**Comment by nixel2007** [comment]
You can clone repo to the atom packages folder and run `npm install` inside

**Comment by collegeimprovements** [comment]
I've configured the proxy and now able to run `git clone` and other git commands. However `npm install` and `apm install` both gives the similar error mentioned above regardless of proxy is set or not.

However, I'm able to install several other atom packages with `apm install package-name` command and also through atom's gui. I'm able to install other packages with and without proxy. 

There might be something that runs some script which is tied to github and hence causing the issue. I can try to manually execute that script and then try it again. If possible please guide me here. (Note: I don't know much about this, it's just a wild guess.)

**Comment by collegeimprovements** [comment]
VS-Code solves the issue.
