### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by dialogchat** [rgbkrk/atom-script#1326]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.14.1

### Stack Trace

Uncaught SyntaxError: Unexpected identifier

```
At /usr/share/atom/resources/app.asar/src/native-compile-cache.js:82

SyntaxError: Unexpected identifier
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/script/lib/code-context-builder.js:5:41)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/script/lib/script.js:3:43)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
    at PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:785:34)
    at PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:430:16)
    at PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:422:12)
    at /app.asar/node_modules/settings-view/lib/package-card.js:719:16
    at /app.asar/node_modules/settings-view/lib/package-card.js:802:11
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:652:27)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:491:26
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  2x -3:11.3.0 editor:toggle-line-comments (input.hidden-input)
     -2:16.7.0 markdown-preview:toggle (input.hidden-input)
  2x -1:51.3.0 script:run (input.hidden-input)
     -1:40 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -1:30.6.0 script:run (input.hidden-input)
     -1:16.8.0 core:confirm (input.hidden-input)
     -0:54.2.0 core:backspace (input.hidden-input)
     -0:39.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.8.63 
platformio-ide-terminal 2.5.0 
python-tools 0.6.9 
script 3.14.1 
```

**Comment by dialogchat** [comment]
I changed my commenting key  binding to ctrl-e. after that I wasn't able to run a Python file in Atom anymore. A re-install of script gave the issue above.
