### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lang' of null

### ISSUE THREAD

**Issue by zombieknee** [rgbkrk/atom-script#1338]
[Enter steps to reproduce:]

1. Tried to save profile
2. 

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.14.1

### Stack Trace

Uncaught TypeError: Cannot read property 'lang' of null

```
At C:\Users\ClintonS\.atom\packages\script\lib\script.js:108

TypeError: Cannot read property 'lang' of null
    at /packages/script/lib/script.js:108:33
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at /packages/script/lib/script-options-view.js:170:20
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at /packages/script/lib/script-input-view.js:45:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -3:04.3.0 script:run (input.hidden-input)
     -2:57.2.0 key-binding-resolver:toggle (input.hidden-input)
     -2:55.3.0 settings-view:open (input.hidden-input)
  2x -2:51.7.0 fuzzy-finder:toggle-git-status-finder (div.package-detail.panels-item)
  5x -2:40.1.0 script:run (input.hidden-input)
     -2:23.5.0 script:run-options (input.hidden-input)
  2x -1:56.7.0 settings-view:open (input.hidden-input)
     -1:55.3.0 key-binding-resolver:toggle (div.package-detail.panels-item)
     -1:39.2.0 core:paste (input.hidden-input)
     -1:15.9.0 core:move-right (input.hidden-input)
     -1:15.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
 12x -1:15.2.0 core:backspace (input.hidden-input)
     -1:04.2.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -1:01.1.0 script:run (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:32 script:run-options (div.tool-panel.tree-view)
  2x -0:19.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-robot-framework 3.3.0 
build 0.67.0 
build-python 0.9.1 
busy 0.7.0 
drnet-config-syntax 0.0.0 
git-difftool 0.2.7 
git-plus 7.8.0 
git-time-machine 1.5.9 
hyperclick 0.0.40 
hyperclick-robot-framework 1.6.0 
language-generic-config 1.3.0 
language-robot-framework 2.2.0 
script 3.14.1 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by ooodragon94** [comment]
same prob here...

**Comment by Skoyer** [comment]
same prob here...
windows 10

**Comment by uso212** [comment]
Got the same issue but running on macOS Mojave

**Comment by chaz2k** [comment]
When will this be fixed?

**Comment by pythseq** [comment]
The same prob in macos lastest vesrion any  advice  ????

**Comment by ekrace** [comment]
Reinstalling the package via APM helped me
`apm uninstall script`
`sudo apm install script` 

for Windows maybe uninstall from within Atom, close it. Run as admin, install the package again. Close Atom again and reopen so the package is loaded correctly. Then try to save a profile again.

**Comment by yinuozhang-econ** [comment]
I tried the above for windows, still doesn't work.
