### ISSUE TITLE
Uncaught TypeError: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by aphoria** [rgbkrk/atom-script#1339]
[Enter steps to reproduce:]

1. Open "Configure Run Options" window.
2. Specify "Command Arguments" or "Program Arguments" for a vbscript.
3. Click Run.

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.14.1

### Stack Trace

Uncaught TypeError: Cannot read property 'concat' of undefined

```
At C:\Users\<username>\.atom\packages\script\lib\script-options-view.js:103

TypeError: Cannot read property 'concat' of undefined
    at /packages/script/lib/script-options-view.js:103:41
    at Array.forEach (native)
    at ScriptOptionsView.splitArgs (/packages/script/lib/script-options-view.js:102:13)
    at ScriptOptionsView.getOptions (/packages/script/lib/script-options-view.js:136:24)
    at ScriptOptionsView.saveOptions (/packages/script/lib/script-options-view.js:141:26)
    at ScriptOptionsView.run (/packages/script/lib/script-options-view.js:195:10)
    at /packages/script/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:15.4.0 core:paste (input.hidden-input)
     -2:06.9.0 editor:move-to-first-character-of-line (input.hidden-input)
     -2:05.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:59.8.0 core:cut (input.hidden-input)
     -1:58.9.0 script:run (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:12.5.0 script:run-options (input.hidden-input)
     -1:10.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:10.1.0 core:delete (input.hidden-input)
     -1:09.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:09.6.0 core:backspace (input.hidden-input)
     -1:07.8.0 script:run (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.3.0 script:run-options (input.hidden-input)
     -0:48.5.0 core:backspace (input.hidden-input)
     -0:47.1.0 script:run (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:39.3.0 script:run-options (input.hidden-input)
     -0:36.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
language-vbscript 0.9.0 
script 3.14.1 
```

**Comment by ostrokach** [comment]
I also get this error if I specify command arguments that contain quotes: `--message "Hello World"`
