### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by rajath95** [rgbkrk/atom-script#1373]
Cannot find module 'electron'
Hide Stack Trace
Error: Cannot find module 'electron'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/rajath/.atom/packages/script/lib/grammars.coffee:7:9)
    at Object.<anonymous> (/home/rajath/.atom/packages/script/lib/grammars.coffee:4:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/rajath/.atom/packages/script/lib/code-context-builder.js:5:41)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/rajath/.atom/packages/script/lib/script.js:3:43)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:172:16)
    at /usr/share/atom/resources/app.asar/src/package.js:800:25

**Comment by tflats** [comment]
it cant find uuid for me

**Comment by salamancajr** [comment]
same for me, sorry to see there's been no reply as of yet

**Comment by dustrdz** [comment]
I have the same issue. No one knows how to fix?

**Comment by geniusupgrader** [comment]
I had this error, too, when forking atom-script and cloning into ~/.atom/packages. After executing `apm install` in the same directory my problem was solved.

**Comment by somedadaism** [comment]
Same here.

**Comment by JoarGjersund** [comment]
This problem happened to me as well. The reason was I cloned the repo into .atom/packages which already had the script package installed. Deleting the folder atom-script fixed the problem for me.

**Comment by llealf01** [comment]
Hello, I have tried the suggestions in this thread and I still can't get it to work... Any suggestions? Thx!

**Comment by pashapanther** [comment]
Try running it from the command line. Are you using atom?

________________________________

**Comment by LucasArruda** [comment]
`apm install script` solves the problem (with `uuid` at least)

**Comment by mikcc123** [comment]
![eec62fed2780724a2a45dee87f60980](https://user-images.githubusercontent.com/52337606/66281570-83a50000-e8ee-11e9-966c-1f5eb95d0072.png)

**Comment by mikcc123** [comment]
求解决方案

**Comment by mikcc123** [comment]
Help   Solution

**Comment by satya379** [comment]
facing the same problem.?

**Comment by motoy-asaph-musan** [comment]
![atom error](https://user-images.githubusercontent.com/66707555/95039206-cb649000-06d8-11eb-97eb-fdd5cff6ec76.PNG)
