### ISSUE TITLE
Uncaught Error: Can't save a buffer with no file

### ISSUE THREAD

**Issue by GabrielCabrera** [rgbkrk/atom-script#1402]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.15.0

### Stack Trace

Uncaught Error: Can't save a buffer with no file

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1183

Error: Can't save a buffer with no file
    at TextBuffer.module.exports.TextBuffer.saveTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1183:21)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1167:25)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1003:32)
    at CodeContextBuilder.buildCodeContext (/packages/script/lib/code-context-builder.js:35:14)
    at Runtime.execute (/packages/script/lib/runtime.js:55:49)
    at HTMLElement.scriptRunByLineNumber (/packages/script/lib/script.js:97:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -1:29.8.0 core:backspace (input.hidden-input)
     -1:25.2.0 editor:select-line (input.hidden-input)
     -1:22.6.0 script:run (input.hidden-input)
     -1:17.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:16.4.0 core:confirm (input.hidden-input)
     -1:14.7.0 core:save (input.hidden-input)
     -1:10.8.0 script:run (input.hidden-input)
  2x -0:43.6.0 editor:newline (input.hidden-input)
     -0:37.5.0 core:save (input.hidden-input)
     -0:35 script:run (input.hidden-input)
     -0:30.8.0 script:run-options (input.hidden-input)
     -0:23 editor:consolidate-selections (input.hidden-input)
     -0:23 core:cancel (input.hidden-input)
     -0:15.4.0 script:run-by-line-number (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
file-icons 2.1.10 
intentions 1.1.5 
linter 2.2.0 
linter-rubocop 2.1.1 
linter-ui-default 1.6.5 
rails-model-schema 0.9.0 
script 3.15.0 
svg-preview 0.11.0 
```

**Comment by AmrSultn** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 ia32
**Electron**: 1.7.11
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.17.3


### Stack Trace

Uncaught Error: Can't save a buffer with no file

```
At C:\Users\amr\AppData\Local\atom\app-1.25.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1305

Error: Can't save a buffer with no file
    at TextBuffer.module.exports.TextBuffer.saveTo (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1305:21)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1289:25)
    at TextEditor.save (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor.js:1148:38)
    at CodeContextBuilder.buildCodeContext (/packages/script/lib/code-context-builder.js:35:14)
    at Runtime.execute (/packages/script/lib/runtime.js:55:49)
    at HTMLElement.scriptRunByLineNumber (/packages/script/lib/script.js:97:55)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.25.0/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.25.0/resources/app/src/atom-environment.js:1343:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.25.0/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
  2x -3:36.8.0 script:run (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:05.3.0 script:run-by-line-number (input.hidden-input)
     -2:14.5.0 script:run (input.hidden-input)
     -2:03.0 script:run-by-line-number (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.6 
atom-runner 2.7.1 
atom-test-runner 0.11.1 
autocomplete-python 1.10.5 
grunt-runner 0.14.0 
Hydrogen 2.3.0 
my-package 0.0.0 
my-theme-syntax 0.0.0 
script 3.17.3 
```
