### ISSUE TITLE
"Expected 11, got 13" error anytime 'atom' is required.

### ISSUE THREAD

**Issue by maschs** [rgbkrk/atom-script#144]
I have no idea why this happens, but I can trace it down to running a coffee-script with 'atom' required:

```
Error: Module version mismatch. Expected 11, got 13.
  at Module.load (/usr/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at bindings (/usr/local/share/atom/resources/app/node_modules/pathwatcher/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:6:32)
  at Object.<anonymous> (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:15:10)
  at Object.<anonymous> (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:954:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/share/atom/resources/app/exports/atom.js:4:10)
  at Object.<anonymous> (/usr/local/share/atom/resources/app/exports/atom.js:28:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/squirtle/github/git-plus/lib/views/select-list-multiple-view.coffee:2:33)
  at Object.<anonymous> (/home/squirtle/github/git-plus/lib/views/select-list-multiple-view.coffee:1:1)
  at Module._compile (module.js:456:26)
```

I've spent the day trying:
- Different node versions
- Different coffee versions
- Building atom with node versions v0.10.x and v0.11.x

I'm using Xubuntu 14.04.

Nothing I could do. Works perfectly, aslong as I don't include `atom` anywhere. Ideas? :weary:

**Comment by EntilZha** [comment]
Closing due to age, reopen if its an issue still
