### ISSUE TITLE
Uncaught Error: Cannot find module 'property-accessors'

### ISSUE THREAD

**Issue by ZephyrG** [rgbkrk/atom-script#1471]
[Enter steps to reproduce:]

1. install markdown-preview-plus
2. Toggle preview

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.17.3

### Stack Trace

Uncaught Error: Cannot find module 'property-accessors'

```
At /Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:0

Error: Cannot find module 'property-accessors'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/script/node_modules/emissary/lib/behavior.js:9:23)
    at /packages/script/node_modules/emissary/lib/behavior.js:120:4)
    at /packages/script/node_modules/emissary/lib/behavior.js:122:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/script/node_modules/emissary/lib/helpers.js:5:14)
    at /packages/script/node_modules/emissary/lib/helpers.js:55:4)
    at /packages/script/node_modules/emissary/lib/helpers.js:57:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/script/node_modules/emissary/lib/emissary.js:4:13)
    at /packages/script/node_modules/emissary/lib/emissary.js:14:4)
    at /packages/script/node_modules/emissary/lib/emissary.js:16:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
```

### Commands

```
     -4:12.9.0 core:backspace (input.hidden-input)
  2x -3:39.6.0 core:paste (input.hidden-input)
     -3:19.4.0 core:save (input.hidden-input)
     -1:07.4.0 markdown-preview-plus:toggle (input.hidden-input)
     -1:00.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-latex 0.8.2 
markdown-preview-plus 2.4.16 
script 3.17.3 
```

**Comment by ZephyrG** [comment]
So it works fine now after I uninstall and reinstall the packages... I am closing this...
