### ISSUE TITLE
Missing weights file in darkflow

### ISSUE THREAD

**Issue by H4k4n61** [rgbkrk/atom-script#1586]
I use Windows 10. I install YOLOv2 608x608 weights in [link](https://pjreddie.com/darknet/yolo/) . After that I pasted it into the bin file. I use cmd and run `python flow --model cfg/yolo.cfg --load bin/yolov2.weights --demo deneme.mp4 --gpu 0.4 --saveVideo` this is work. After that set up atom and I add enviroment in script (I use anaconda). I run this code.
`import cv2
from darkflow.net.build import TFNet
import numpy
option = {
'model': 'cfg/yolo.cfg',
'load': 'bin/yolov2.weights',
'threshold': 0.15,
'gpu': 0.5
}

tfnet = TFNet(option) `

give error

Traceback (most recent call last):
File "C:\Users\Hakan\Desktop\object\darkflow-master\figure.py", line 11, in 
tfnet = TFNet(option)
File "C:\Users\Hakan\Desktop\object\darkflow-master\darkflow\net\build.py", line 58, in init
darknet = Darknet(FLAGS)
File "C:\Users\Hakan\Desktop\object\darkflow-master\darkflow\dark\darknet.py", line 13, in init
self.get_weight_src(FLAGS)
File "C:\Users\Hakan\Desktop\object\darkflow-master\darkflow\dark\darknet.py", line 47, in get_weight_src
'{} not found'.format(FLAGS.load)
AssertionError: bin/yolov2.weights not found

If I can use cmd or pycharm and run same code , is work. no errors have occurred. I use the same environment (anaconda) while using pycharm and cmd. I don't understand the cause of error. Please help

**Comment by H4k4n61** [comment]
Windows not give access permit. Solve problem.
