### ISSUE TITLE
Issues running Kotlin

### ISSUE THREAD

**Issue by Saplyng** [rgbkrk/atom-script#1705]
Script cant seem to run Kotlin, attempted with kotlin Hello, World. The code will run via command line, but not with Script

fun main(args: Array<String>) {
  println("Hello, World")
}

results in the following error:
[Command: cmd '/c kotlinc C:\Users\Sapli\Documents\GitHub\Hello-World-redux\Kotlin\HelloWorld.kt -include-runtime -d /tmp/HelloWorld.jar && java -jar /tmp/HelloWorld.jar']
exception: org.jetbrains.kotlin.cli.jvm.compiler.CompileEnvironmentException: Invalid jar path \tmp\HelloWorld.jar
	at org.jetbrains.kotlin.cli.jvm.compiler.CompileEnvironmentUtil.writeToJar(CompileEnvironmentUtil.java:108)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.writeOutput(KotlinToJVMBytecodeCompiler.kt:84)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileBunchOfSources(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:200)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:94)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:88)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:66)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:34)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:180)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:171)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:341)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jetbrains.kotlin.preloading.Preloader.run(Preloader.java:81)
	at org.jetbrains.kotlin.preloading.Preloader.main(Preloader.java:43)
Caused by: java.io.FileNotFoundException: \tmp\HelloWorld.jar (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at org.jetbrains.kotlin.cli.jvm.compiler.CompileEnvironmentUtil.writeToJar(CompileEnvironmentUtil.java:103)
	... 19 more

[Finished in 2.688s]

**Comment by DamnedScholar** [comment]
This looks like an issue with [how Kotlin support is written](https://github.com/rgbkrk/atom-script/blob/master/lib/grammars/java.coffee#L34). Obviously, Windows doesn't have a `/tmp/`. I don't know much about Kotlin; is there supposed to be a `tmp/` folder inside of your project folder? Does it work to run your code by selection instead of by file?

**Comment by Saplyng** [comment]
to my (very limited) knowledge, it doesn't need a tmp / folder to run because it will compile via cmd or in IDEA. running code by line isn't supported for kotlin.

**Comment by DamnedScholar** [comment]
Then you may be best off running it from the command line using a package like `process-palette` or `termination`.

**Comment by Saplyng** [comment]
Alight, will do. I'll close the issue, but maybe a note should be added that Script can't run kotlin on windows?
