### ISSUE TITLE
Uncaught Error: Cannot find module './lib/rng'

### ISSUE THREAD

**Issue by DanWaffle** [rgbkrk/atom-script#1726]
Steps to re

1. Fresh Install of Atom
2. Install atom-script 
3. Restart Atom

**Atom**: 1.31.1 ia32
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.18.1

### Stack Trace

Uncaught Error: Cannot find module './lib/rng'

```
At module.js:545

Error: Cannot find module './lib/rng'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.31.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.31.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.31.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/script/node_modules/uuid/v1.js:1:166)
    at /packages/script/node_modules/uuid/v1.js:111:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.31.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/script/node_modules/uuid/index.js:1:165)
    at /packages/script/node_modules/uuid/index.js:10:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.31.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/script/lib/grammar-utils.js:6:24)
    at /packages/script/lib/grammar-utils.js:109:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Non-Core Packages

```
autocomplete-python 1.10.12 
script 3.18.1 
```

**Comment by DanWaffle** [comment]
Fixed by running -safe and uninstalling script then reinstalling it with admin privileges.
