### ISSUE TITLE
Uncaught Error: Cannot find module 'uuid'Require stack:- $ATOM_HOME/packages\script\lib\grammar...

### ISSUE THREAD

**Issue by Sampath-sumedh-Dinavahi** [rgbkrk/atom-script#2332]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.26.0

### Stack Trace

Uncaught Error: Cannot find module 'uuid'
Require stack:
- C:\Users\hp\.atom\packages\script\lib\grammar-utils.js
- C:\Users\hp\.atom\packages\script\lib\grammars\index.coffee
- C:\Users\hp\.atom\packages\script\lib\grammars.js
- C:\Users\hp\.atom\packages\script\lib\code-context-builder.js
- C:\Users\hp\.atom\packages\script\lib\script.js
- C:\Users\hp\atom\app-1.53.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module 'uuid'
Require stack:
- C:\Users\hp\.atom\packages\script\lib\grammar-utils.js
- C:\Users\hp\.atom\packages\script\lib\grammars\index.coffee
- C:\Users\hp\.atom\packages\script\lib\grammars.js
- C:\Users\hp\.atom\packages\script\lib\code-context-builder.js
- C:\Users\hp\.atom\packages\script\lib\script.js
- C:\Users\hp\atom\app-1.53.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/script/lib/grammar-utils.js:6:24)
    at /packages/script/lib/grammar-utils.js:109:2)
    at Module.get_Module._compile (~/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/script/lib/grammars/index.coffee:5:45)
    at /packages/script/lib/grammars/index.coffee:4:1)
    at /packages/script/lib/grammars/index.coffee:4:1)
    at Module.get_Module._compile (~/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (~/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/script/lib/grammars.js:9:28)
    at /packages/script/lib/grammars.js:1:13)
    at Module.get_Module._compile (~/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
```

### Commands

```
     -0:31.7.0 core:save (input.hidden-input)
     -0:25.6.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
script 3.26.0 
```

**Comment by Sampath-sumedh-Dinavahi** [comment]
Pls find a solution for this
