### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by madyhac** [rgbkrk/atom-script#2791]
"apm install script" then it says 
C:\Users\>apm install script
Installing script to C:\Users\no name bro\.atom\packages C:\Users\no name bro\AppData\Local\atom\app-1.60.0\resources\app\apm\lib\install.js:256
          if (body.releases.latest) {
                            ^

TypeError: Cannot read property 'latest' of undefined
    at C:\Users\no name bro\AppData\Local\atom\app-1.60.0\resources\app\apm\lib\install.js:256:29
    at Request._callback (C:\Users\no name bro\AppData\Local\atom\app-1.60.0\resources\app\apm\lib\request.js:57:22)
    at Request.self.callback (C:\Users\no name bro\AppData\Local\atom\app-1.60.0\resources\app\apm\node_modules\request\request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (C:\Users\no name bro\AppData\Local\atom\app-1.60.0\resources\app\apm\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (C:\Users\no name bro\AppData\Local\atom\app-1.60.0\resources\app\apm\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)

C:\Users\no name bro>

**Comment by EchoHayate** [comment]
Same error! Waiting for the solution.

**Comment by tbscer** [comment]
years passed, still no solution

**Comment by nortikin** [comment]
the same
