### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by muukii** [rgbkrk/atom-script#306]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.3
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v2.18.0
### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At child_process.js:1160

Error: spawn ENOTDIR
  at exports._errnoException (util.js:753:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
  at ScriptView.module.exports.ScriptView.run (/Users/Muukii/dotfiles/dotfiles/.atom/packages/script/lib/script-view.coffee:257:28)
  at ScriptView.module.exports.ScriptView.start (/Users/Muukii/dotfiles/dotfiles/.atom/packages/script/lib/script-view.coffee:117:6)
  at ScriptView.module.exports.ScriptView.defaultRun (/Users/Muukii/dotfiles/dotfiles/.atom/packages/script/lib/script-view.coffee:82:6)
  at atom-workspace.<anonymous> (/Users/Muukii/dotfiles/dotfiles/.atom/packages/script/lib/script-view.coffee:30:59)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```
### Commands

```
     -0:26.9 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.insert-mode)
  2x -0:25.9 core:close (atom-text-editor.editor.vim-mode.insert-mode)
     -0:22.8 application:new-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-fruits.theme-spacegray-dark-ui)
     -0:20.2 grammar-selector:show (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:18.5 core:backspace (atom-text-editor.editor.mini)
     -0:16.7 core:confirm (atom-text-editor.editor.mini)
     -0:16.2 script:run (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:08.1 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.6 script:run (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "minimap",
      "emmet"
    ],
    "themes": [
      "spacegray-dark-ui",
      "fruits"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-alignment, v0.11.0
atom-jshint, v1.5.0
autoclose-html, v0.15.0
autocomplete-emojis, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
autocomplete-snippets, v1.0.1
bracket-matcher, v0.71.0
color, v0.5.0
color-picker, v1.4.4
command-logger, v0.22.0
compare-files, v0.4.1
editor-stats, v0.17.0
file-icons, v1.4.11
filetype-color, v0.1.4
font-viewer, v0.1.0
fruits, v5.0.0
git-diff, v0.54.0
git-log, v0.3.0
go-format, v1.0.7
go-plus, v3.2.2
keybinding-resolver, v0.29.0
language-docker, v1.1.2
language-swift, v0.3.0
linter, v0.12.0
pdf-view, v0.17.0
processing-language, v0.1.0
project-manager, v1.15.5
recent-files, v0.3.0
regex-railroad-diagram, v0.7.1
remember-session, v0.5.1
remote-edit, v1.6.4
remote-sync, v2.4.0
script, v2.18.0
spacegray-dark-ui, v0.6.0
vim-mode, v0.34.0
visual-bell, v1.0.0
webbox-color, v0.5.4

# Dev
No dev packages
```

**Comment by erran** [comment]
@muukii0803 Could you fill in the steps to reproduce please?
