### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by cmelgarejo** [rgbkrk/atom-script#327]
[Enter steps to reproduce below:]

1. Install the script package,
2. Profit? :(

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v2.18.0

### Stack Trace

Failed to activate the script package

```
At undefined is not a function

TypeError: undefined is not a function
  at ScriptOptionsView.module.exports.ScriptOptionsView.initialize (C:\Users\Christian\.atom\packages\script\lib\script-options-view.coffee:51:37)
  at ScriptOptionsView.View (C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new ScriptOptionsView (C:\Users\Christian\.atom\packages\script\lib\script-options-view.coffee:6:3)
  at Object.module.exports.activate (C:\Users\Christian\.atom\packages\script\lib\script.coffee:28:30)
  at Package.module.exports.Package.activateNow (C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:240:19)
  at C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:465:21)
  at C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Christian\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -2:19.2 core:move-left (atom-text-editor.editor.is-focused)
  3x -2:18.8 core:select-left (atom-text-editor.editor.is-focused)
     -2:08.4 core:move-up (atom-text-editor.editor.is-focused)
  3x -2:07.8 core:select-left (atom-text-editor.editor.is-focused)
  3x -2:05.7 core:move-down (atom-text-editor.editor.is-focused)
     -2:05.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:04.5 core:move-down (atom-text-editor.editor.is-focused)
     -2:04.2 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:03.9 core:move-right (atom-text-editor.editor.is-focused)
  4x -2:03.5 core:select-left (atom-text-editor.editor.is-focused)
  8x -2:02.1 core:move-up (atom-text-editor.editor.is-focused)
  8x -2:00.5 core:move-down (atom-text-editor.editor.is-focused)
     -1:59.3 core:move-up (atom-text-editor.editor.is-focused)
     -1:58.7 core:save (atom-text-editor.editor.is-focused)
  2x -1:57.2 core:close (atom-text-editor.editor.is-focused)
     -1:54.5 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
script, v2.18.0

# Dev
No dev packages
```

**Comment by steve-ross** [comment]
Having the same issue after updating to 0.192.0

**Comment by mvl** [comment]
oh interesting - I just had this happen when going from Atom 0.196 to 0.198.

**Comment by rgbkrk** [comment]
I just updated everything (including Atom), and it's working perfectly for me. Script version is 2.21.0.
