### ISSUE TITLE
Failed to load the atom-script package (cannot find module underscore)

### ISSUE THREAD

**Issue by theocodes** [rgbkrk/atom-script#360]
[Enter steps to reproduce below:]

1. Install package
2. Run atom

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-script](https://github.com/rgbkrk/atom-script) package, v2.18.0

### Stack Trace

Failed to load the atom-script package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/atom-script/lib/grammars.coffee:4:5)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/atom-script/lib/grammars.coffee:4:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/atom-script/lib/script-view.coffee:1:14)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/atom-script/lib/script-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/atom-script/lib/script.coffee:1:14)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/atom-script/lib/script.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:51:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-script, v2.18.0
elixir-cmd, v0.2.5
iex, v0.8.6
language-elixir, v0.3.4
linter-elixirc, v0.2.1
minimap-git-diff, v4.1.2

# Dev
No dev packages
```

**Comment by erran** [comment]
@theocodes Was this resolved for you in the last update? Underscore has been in script's `package.json` for a long time now (`"underscore": "~1.5.2",`).

**Comment by rgbkrk** [comment]
Sometimes a full reload needs to take effect after an update with Atom. If that doesn't address, happy to help debug further.

**Comment by theocodes** [comment]
Yes, it's working for me! Thanks

**Comment by benjavides** [comment]
Atom is giving me this same error everytime I try to run code. I reloaded atom, reinstalled it, even formatted my computer and nothing works. Please help

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v2.29.0


### Stack Trace

Failed to activate the script package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\script\lib\grammars.coffee:4:5)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\script\lib\grammars.coffee:4:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\script\lib\script-view.coffee:1:14)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\script\lib\script-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\script\lib\script.coffee:1:14)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\script\lib\script.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:263:14)
  at Package.module.exports.Package.activateNow (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:241:14)
  at C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:838:25
  at Emitter.module.exports.Emitter.emit (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:226:20)
  at C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -0:05.3.0 script:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.4
linter, v1.6.0
linter-flake8, v1.6.1
linter-pep8, v1.0.1
linter-pylint, v1.0.0
script, v2.29.0

# Dev
No dev packages
```

**Comment by sugasikao** [comment]
Maybe you need to install 'underscore'.

**Try Install.**
`npm install underscore`

**Comment by tommybutler** [comment]
1. Just installed atom latest release (1.17.2 x64).
2. Just installed script package manually via latest release from https://github.com/rgbkrk/atom-script/releases/tag/v3.15.0

Notes: underscore is listed as prerequisite in latest release -- 
https://github.com/rgbkrk/atom-script/blob/v3.15.0/package.json#L339

```
Cannot find module 'underscore'
Hide Stack Trace
Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\module-cache.js:354:1)
    at Module.require (file:///C:/Users/tb40062/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (file:///C:/Users/tb40062/.atom/packages/atom-script-3.15.0/lib/grammars.coffee:4:5)
    at Object.<anonymous> (file:///C:/Users/tb40062/.atom/packages/atom-script-3.15.0/lib/grammars.coffee:4:1)
    at Module.get_Module._compile (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .coffee] (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///C:/Users/tb40062/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (file:///C:/Users/tb40062/.atom/packages/atom-script-3.15.0/lib/code-context-builder.js:5:41)
    at Module.get_Module._compile (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///C:/Users/tb40062/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (file:///C:/Users/tb40062/.atom/packages/atom-script-3.15.0/lib/script.js:3:43)
    at Module.get_Module._compile (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (C:\Users\tb40062\AppData\Local\atom\app-1.17.2\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///C:/Users/tb40062/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
```

**Comment by nakovskii** [comment]
Still having issues with javascript...
bash: /home/boss/.atom/packages/script/node_modules/.bin/babel: No such file or directory

how to correct it?

**Comment by mevanloon** [comment]
@nakovskii I have the same issue on a vanilla install of atom-script. I've worked around the issue by creating custom run options:
`Command: node`
`Command Arguments: {FILE_ACTIVE}`
