### ISSUE TITLE
Cannot read property 'prependToTop' of undefined

### ISSUE THREAD

**Issue by Huaraz2** [rgbkrk/atom-script#380]
[Enter steps to reproduce below:]

1.  Open atom in 1.0 API preview mode.

**Atom Version**: 0.190.0-d9f0f23
**System**: linux 3.16.0-33-generic
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v2.18.0

### Stack Trace

Failed to activate the script package

```
At Cannot read property 'prependToTop' of undefined

TypeError: Cannot read property 'prependToTop' of undefined
    at ScriptOptionsView.module.exports.ScriptOptionsView.initialize (/home/huaraz2/.atom/packages/script/lib/script-options-view.coffee:115:25)
    at ScriptOptionsView.View (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ScriptOptionsView (/home/huaraz2/.atom/packages/script/lib/script-options-view.coffee:12:54)
    at Object.module.exports.activate (/home/huaraz2/.atom/packages/script/lib/script.coffee:36:32)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:19)
    at /usr/share/atom/resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:435:21)
    at /usr/share/atom/resources/app/src/package-manager.js:419:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "highlight-line"
    ],
    "themes": [
      "atom-dark-ui",
      "the--matrix-syntax"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.9.0
color-picker, v1.6.0
minimap, v4.7.6
script, v2.18.0
the--matrix-syntax, v1.0.0

# Dev
No dev packages
```

**Comment by erran** [comment]
See #377, #384, #395, #396, and finally #407 which resolves this.
