### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by nanorepublica** [rgbkrk/atom-script#395]
[Enter steps to reproduce below:]

1.  Start Atom - happens everytime

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v2.19.0

### Stack Trace

Failed to activate the script package

```
At Cannot read property 'prependToTop' of undefined

TypeError: Cannot read property 'prependToTop' of undefined
    at ScriptOptionsView.module.exports.ScriptOptionsView.initialize (/Users/amiller/.atom/packages/script/lib/script-options-view.coffee:115:25)
    at ScriptOptionsView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ScriptOptionsView (/Users/amiller/.atom/packages/script/lib/script-options-view.coffee:12:54)
    at Object.module.exports.activate (/Users/amiller/.atom/packages/script/lib/script.coffee:36:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "travis-ci-status"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/amiller"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
angularjs-helper, v0.8.0
angularjs-snippets, v0.10.2
atom-angularjs, v0.1.2
atom-cli-diff, v0.11.0
atom-django, v0.2.1
atom-jinja2, v0.5.0
atom-runner, v2.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
build, v0.29.0
color-picker, v1.7.0
command-logger, v0.23.0
django-templates, v0.4.0
editor-stats, v0.17.0
eval, v0.2.0
git-blame, v0.4.0
git-go, v1.0.1
git-grep, v0.9.0
git-history, v2.5.0
git-log, v0.3.0
git-tab-status, v1.7.0
inline-autocomplete, v1.0.4
jsonlint, v1.1.0
language-django, v0.1.1
language-docker, v1.1.3
language-puppet, v0.11.0
language-python-django-templates, v0.1.0
linter, v0.12.0
linter-puppet, v0.1.0
linter-puppet-lint, v0.2.8
minimap, v4.7.6
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
monokai, v0.14.0
pretty-json, v0.3.3
project-colorize, v0.1.0
project-manager, v1.15.5
project-ring, v0.19.6
recent-files, v0.3.0
recent-projects, v0.3.0
script, v2.19.0
set-syntax, v0.2.1
update-packages, v0.1.0

# Dev
No dev packages
```

**Comment by erran** [comment]
Closing this ticket since the duplicate #396 is fixed by #407.
