### ISSUE TITLE
Uncaught TypeError: undefined is not a function in 1.0 API Preview Mode

### ISSUE THREAD

**Issue by davidbarsky** [rgbkrk/atom-script#435]
This issue does **not** happen when Atom isn’t launched using the preview mode. It is also not shell dependent, as I’ve tried plenty of possible variations (Atom 1.0 API Preview Mode, `bash`/`zsh`/`fish`).

### Step Reproduction

1. Run `atom --one` in a directory.
2. Run `atom-script` on the file.
3. Get the “Uncaught TypeError...” alert.

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v2.21.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/David/.atom/packages/script/lib/script-view.coffee:236

TypeError: undefined is not a function
  at ScriptView.module.exports.ScriptView.run (/Users/David/.atom/packages/script/lib/script-view.coffee:236:10)
  at ScriptView.module.exports.ScriptView.start (/Users/David/.atom/packages/script/lib/script-view.coffee:120:6)
  at ScriptView.module.exports.ScriptView.defaultRun (/Users/David/.atom/packages/script/lib/script-view.coffee:85:6)
  at atom-workspace.subscriptions.add.atom.commands.add.script:run (/Users/David/.atom/packages/script/lib/script-view.coffee:37:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:00.6.0 script:run (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-ruby",
      "symbols-view",
      "wrap-guide",
      "space-tab"
    ],
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v3.2.0
atom-pair, v1.1.5
autocomplete-plus, v2.13.1
language-fish-shell, v1.0.2
language-haml, v0.20.0
language-scheme, v1.4.0
language-slim, v0.4.0
language-swift, v0.4.0
linter, v0.12.2
linter-flow, v0.1.4
linter-scss-lint, v0.0.14
rspec, v0.3.0
script, v2.21.0
tabs-to-spaces, v0.10.0
vim-mode, v0.46.0

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
Oh boy, can definitely reproduce. Thanks for the heads up.

**Comment by erran** [comment]
@davidbarksy Thanks even more for the reproduction steps. I forgot what those looked like for a while.

**Comment by rgbkrk** [comment]
Yeah... we're not using the right messaging API, which effects Atom achievements too.

```CoffeeScript
atom.emit 'achievement:unlock', msg: 'Homestar Runner'
```

**Comment by rgbkrk** [comment]
Deleted the offending code in #436.

**Comment by davidbarsky** [comment]
@rgbkrk @erran happy to help! :+1:
