### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by benjavides** [rgbkrk/atom-script#597]
Every time I try to run the code in atom this shows up:
![0](https://cloud.githubusercontent.com/assets/7333792/10125428/01d95a70-654a-11e5-8311-09597acdcb20.PNG)
I tried reinstalling atom, updating the packages, even formatting my computer but nothing works. Please help.
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v2.29.0

### Stack Trace

Failed to activate the script package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\script\lib\grammars.coffee:4:5)
    at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\script\lib\grammars.coffee:4:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
     -0:04.4.0 script:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.4
linter, v1.6.0
linter-flake8, v1.6.1
linter-pep8, v1.0.1
linter-pylint, v1.0.0
script, v2.29.0

# Dev
No dev packages
```

**Comment by benjavides** [comment]
I found the problem thanks to @joaoportela in AtomLinter/linter-flake8#82. 
It was because my **windows 8.1 profile name had a non-Asci character**

**Comment by rgbkrk** [comment]
> It was because my windows 8.1 profile name had a non-Ascii character

Whoa. That's not something I expected to see or be able to debug!

Thanks for reporting and giving it a good effort.
