### ISSUE TITLE
Script fails to show that program has stopped execution

### ISSUE THREAD

**Issue by chrwi** [rgbkrk/atom-script#654]
In previous versions, when running a Python script, the hour glass disappeared when the process was closed either by forcing it or pressing CTRL+Q. Now the hour glass is always there, regardless of the state of the program execution. 

To reproduce, start a python application and let it finish or force close it. 

I am using Windows 7, Git 1.2.1, latest script package. Python 2.7.10 32bit. 

Whenever a python application is finished running, this is what I get:

TypeError: Cannot read property 'toString' of undefined
    at ScriptView.module.exports.ScriptView.setHeaderAndShowExecutionTime (file:///C:/Users/chw1/.atom/packages/script/lib/script-view.coffee:34:53)
    at ScriptView.setHeaderAndShowExecutionTime (file:///C:/Users/chw1/.atom/packages/script/lib/script-view.coffee:1:1)
    at file:///C:/Users/chw1/.atom/packages/script/lib/view-runtime-observer.coffee:15:13
    at Emitter.module.exports.Emitter.emit (C:\Users\chw1\AppData\Local\atom\app-1.2.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Runner.module.exports.Runner.onExit (file:///C:/Users/chw1/.atom/packages/script/lib/runner.coffee:68:14)
    at file:///C:/Users/chw1/.atom/packages/script/lib/runner.coffee:1:1
    at triggerExitCallback (C:\Users\chw1\AppData\Local\atom\app-1.2.1\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\chw1\AppData\Local\atom\app-1.2.1\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by Huaraz2** [comment]
I believe this is fixed in commit ddd0e9ca9cf09bb759ababaf62c3b04a27f51297 just waiting for new version with it in now
