### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lang' of undefined

### ISSUE THREAD

**Issue by AnasFullStack** [rgbkrk/atom-script#671]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v3.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'lang' of undefined

```
At /Users/anas/.atom/packages/script/lib/runtime.coffee:52

TypeError: Cannot read property 'lang' of undefined
    at Runtime.module.exports.Runtime.execute (/Users/anas/.atom/packages/script/lib/runtime.coffee:52:19)
    at atom-workspace.subscriptions.add.atom.commands.add.script:run (/Users/anas/.atom/packages/script/lib/script.coffee:50:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at ScriptOptionsView.module.exports.ScriptOptionsView.run (/Users/anas/.atom/packages/script/lib/script-options-view.coffee:83:19)
    at HTMLButtonElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:19.8.0 core:backspace (div.terminal)
     -5:18.2.0 core:confirm (div.terminal)
  5x -5:10.1.0 core:backspace (atom-workspace.workspace.theme-atom-dark-syntax.theme-one-dark-ui.scrollbars-visible-always)
     -3:58.8.0 project-manager:list-projects (atom-workspace.workspace.theme-atom-dark-syntax.theme-one-dark-ui.scrollbars-visible-always)
     -2:13.3.0 term3:open-split-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  6x -2:10.3.0 core:move-up (atom-pane.pane.active)
     -2:04.1.0 core:move-down (div.terminal)
     -2:03.4.0 core:confirm (div.terminal)
     -1:32.9.0 script:run (atom-pane.pane.active)
     -1:22.9.0 script:run-options (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:05.1.0 term3:copy (div.terminal)
  3x -1:03.9.0 core:paste (input.editor.mini.native-key-bindings)
     -0:55.6.0 core:focus-next (input.editor.mini.native-key-bindings)
     -0:52.2.0 term3:paste (div.terminal)
  2x -0:49 core:paste (input.editor.mini.native-key-bindings)
     -0:18.7.0 script:run (atom-workspace.workspace.theme-atom-dark-syntax.theme-one-dark-ui.scrollbars-visible-always)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint",
      "linter-pylint",
      "atom-typescript"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
aligner, v0.17.3
angularjs, v0.3.3
angularjs-styleguide-snippets, v0.7.3
atom-alignment, v0.12.1
atom-beautify, v0.28.19
atom-django, v0.3.2
atom-fix-path, v0.1.0
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-python, v0.10.7
clipboard-history, v0.6.6
compare-files, v0.6.2
docblockr, v0.7.3
emmet, v2.3.15
file-icons, v1.6.12
fold-functions, v0.4.3
fonts, v1.0.0
highlight-selected, v0.11.1
javascript-snippets, v1.0.0
jshint, v1.8.3
language-dots, v0.0.4
language-x86, v0.1.0
linter, v1.11.3
linter-csslint, v1.1.0
linter-flake8, v1.9.2
linter-htmlhint, v0.2.1
linter-js-standard, v3.2.1
linter-jshint, v1.2.1
livereload, v0.4.4
local-history, v3.2.3
markdown-preview-plus, v2.2.2
meteor-api, v2.20.0
method-separator, v0.1.4
minimap, v4.16.2
minimap-highlight-selected, v4.3.1
nerd-treeview, v0.3.1
open-recent, v4.0.1
pigments, v0.19.1
project-manager, v2.6.5
python-tools, v0.6.7
rest-client, v0.5.0
save-session, v0.15.7
script, v3.0.2
term3, v0.19.2
vim-mode, v0.63.0
vim-surround, v0.8.1
w3c-validation, v0.2.0
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by pchomik** [comment]
In my case I see same issue when all files in the project are closed. Problem disappear when at least one file is open.

**Comment by baubaid** [comment]
Has this issue been resolved? I have the same issue but it does not seem to be affecting anything that I need. Just an annoyance.

**Comment by Dreampie** [comment]
3.7.3  same error
