### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by archerface** [rgbkrk/atom-script#678]
[Enter steps to reproduce below:]

1. Tried to run the Script: Run command in Atom for a Scala program. Then this happened.
2. I did not do anything else.

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Education
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v3.2.0

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, unlink 'D:\Dropbox\personal_projects\Scala\Intro\src\com\jonstefani\scala\HelloWorld.scala~'

```
At C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1030

Error: EBUSY: resource busy or locked, unlink 'D:\Dropbox\personal_projects\Scala\Intro\src\com\jonstefani\scala\HelloWorld.scala~'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:947:18)
    at Function.rimrafSync [as sync] (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\rimraf\rimraf.js:211:13)
    at Object.fsPlus.removeSync (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:272:21)
    at TextBuffer.module.exports.TextBuffer.removeBackupFileAfterWriting (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1126:17)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1023:16)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:557:26)
    at CodeContextBuilder.module.exports.CodeContextBuilder.buildCodeContext (file:///C:/Users/Jonathan/.atom/packages/script/lib/code-context-builder.coffee:34:14)
    at Runtime.module.exports.Runtime.execute (file:///C:/Users/Jonathan/.atom/packages/script/lib/runtime.coffee:48:39)
    at atom-workspace.subscriptions.add.atom.commands.add.script:run (file:///C:/Users/Jonathan/.atom/packages/script/lib/script.coffee:50:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (C:\Users\Jonathan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:35.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 10x -0:32.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:23.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.4.0 script:run (atom-text-editor.editor)
     -0:08.8.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:07.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:03.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.5.0 script:run (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "fonts"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-material-syntax, v0.2.6
atom-material-ui, v0.8.0
build, v0.50.0
build-cargo, v0.9.0
file-icons, v1.6.13
go-plus, v3.5.2
go-rename, v0.3.0
highlight-selected, v0.11.1
language-docker, v1.1.6
language-protobuf, v0.5.0
language-rust, v0.4.5
language-scala, v1.1.4
linter, v1.11.3
linter-rust, v0.2.11
linter-scalac, v1.1.0
minimap, v4.16.2
open-recent, v4.0.1
project-manager, v2.6.5
racer, v0.17.2
rust-api-docs-helper, v0.5.1
scala-format, v0.1.8
script, v3.2.0

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
Interesting. I wonder if this was due to a special bit being set by Dropbox. Not sure how that behaves in Windows.

**Comment by archerface** [comment]
I found the issue was that I did not start atom from command prompt. On other computers it worked without being started from the command prompt because Scala was installed in the default locations. I don't think that the issue is Dropbox.
