### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'atom://config'

### ISSUE THREAD

**Issue by elango** [rgbkrk/atom-script#842]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v3.6.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'atom://config'

```
At fs.js:854

Error: ENOENT: no such file or directory, stat 'atom://config'
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at Runner.module.exports.Runner.args (/Users/elango/.atom/packages/script/lib/runner.coffee:105:28)
    at Runner.module.exports.Runner.run (/Users/elango/.atom/packages/script/lib/runner.coffee:18:13)
    at Runtime.module.exports.Runtime.execute (/Users/elango/.atom/packages/script/lib/runtime.coffee:69:13)
    at atom-workspace.subscriptions.add.atom.commands.add.script:run (/Users/elango/.atom/packages/script/lib/script.coffee:66:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:00.9.0 script:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-ruby"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v1.1.0
atom-ternjs, v0.8.3
autocomplete-python, v1.7.0
color-picker, v2.0.7
go-plus, v3.4.5
minimap, v4.11.2
python-iresolve, v0.0.3
python-isort, v0.0.7
python-tools, v0.6.7
python-yapf, v0.10.0
script, v3.6.0

# Dev
No dev packages
```

**Comment by nixel2007** [comment]
hi, @elango 

what did you do to get this error? open atom, run script, etc?

**Comment by nixel2007** [comment]
Fix inc.
