### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by feapri** [rgbkrk/atom-script#924]
Win 10, ATOM 1.7.3, Python 3.5.1
Installation of script from the settings within packages did nothing (mouse spinning like installation was ongoing but nothing was copied into the .atom\packages\ directory) and no error message was displayed.
I did download script from the repo (.zip) and extracted the contents into the folder .atom\packages\
started ATOM, press CTRL+Shift+B and the error "Failed to activate the script package" was generated
cannot run scripts within ATOM

**Comment by Nollikino** [comment]
I am having the same problem, but with python 2.7.8

Steps to reproduce:

1. Call the Script: Run command on a .py file

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v3.7.1


### Stack Trace

Failed to activate the script package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/<username censored>/.atom/packages/script/lib/grammars.coffee:4:5)
    at Object.<anonymous> (file:///C:/Users/<username censored>/.atom/packages/script/lib/grammars.coffee:4:1)
    at Module._compile (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/<username censored>/.atom/packages/script/lib/code-context-builder.coffee:2:14)
    at Object.<anonymous> (file:///C:/Users/<username censored>/.atom/packages/script/lib/code-context-builder.coffee:1:1)
    at Module._compile (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/<username censored>/.atom/packages/script/lib/script.coffee:1:22)
    at Object.<anonymous> (file:///C:/Users/<username censored>/.atom/packages/script/lib/script.coffee:1:1)
    at Module._compile (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:173:16)
    at C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\command-registry.js:241:20)
    at C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\<username censored>\AppData\Local\atom\app-1.7.4\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:02.9.0 script:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "Peacock"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.19
autocomplete-python, v1.7.3
color-picker, v2.1.1
keyboard-localization, v1.4.18
language-autohotkey, v0.1.0
minimap, v4.24.1
minimap-hide, v0.3.0
remote-edit, v1.8.24
script, v3.7.1
Sublime-Style-Column-Selection, v1.5.1

# Dev
No dev packages
```

**Comment by nixel2007** [comment]
Try to run `apm install` in `C:/Users/<username censored>/.atom/packages/script` directory

**Comment by jenny0621** [comment]
I am having the same problem, how to solve?

**Comment by ivanlflj** [comment]
Hi,
Same thing here, where you able to solve it. I run the `apm install` and it did not solve it.

**Comment by xuezimo** [comment]
I want to run C++ , but it can't do it. Please  give me some advice, thank you .

**Comment by varsha-raj** [comment]
Hi all just a follow up on this- I've been having the same issue and was wondering if anyone found an alternative to this? Thanks!

**Comment by jkilgrow** [comment]
I'm on a corporate development Windows machine. I don't have apm and I am not allowed to install it.
