### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/home/markroxor/Desktop/Summer'16/temp.cpp'

### ISSUE THREAD

**Issue by markroxor** [rgbkrk/atom-script#956]
I tried compiling the cpp program simply by hitting ctrl+shift+B for the first time with "script" package installed.

**Atom Version**: 1.7.4
**System**: Linux Mint
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v3.7.3

### Stack Trace

Uncaught Error: EACCES: permission denied, open '/home/markroxor/Desktop/Summer'16/temp.cpp'

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1108

Error: EACCES: permission denied, open '/home/markroxor/Desktop/Summer'16/temp.cpp'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:420:21)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:377:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1099:19)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at CodeContextBuilder.module.exports.CodeContextBuilder.buildCodeContext (/home/markroxor/.atom/packages/script/lib/code-context-builder.coffee:34:14)
    at Runtime.module.exports.Runtime.execute (/home/markroxor/.atom/packages/script/lib/runtime.coffee:49:39)
    at atom-workspace.subscriptions.add.atom.commands.add.script:run (/home/markroxor/.atom/packages/script/lib/script.coffee:70:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -6:13.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -6:03.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:56.2.0 editor:move-to-previous-subword-boundary (atom-text-editor.editor.is-focused)
  2x -0:41.4.0 script:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
script, v3.7.3

# Dev
No dev packages
```

**Comment by nixel2007** [comment]
can you try to run script from dir without `'` in path?

**Comment by markroxor** [comment]
How to change it. Pardon me I am new to Atom.

**Comment by markroxor** [comment]
Got it.

**Comment by nixel2007** [comment]
just rename the `Summer'16` dir, or put file in another dir

**Comment by markroxor** [comment]
Working fine.

**Comment by markroxor** [comment]
Please supply a fix.
