### ISSUE TITLE
Uncaught TypeError: args.split is not a function

### ISSUE THREAD

**Issue by LightInjectedVenom** [rgbkrk/atom-script#973]
Hi,

[Enter steps to reproduce below:]

1. ... After creating/deleting a profile
2. ... Then trying to create a new profile again

**Atom Version**: 1.8.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v3.7.3

### Stack Trace

Uncaught TypeError: args.split is not a function

```
At /C:/Users/ekaluc/.atom/packages/script/lib/script-options-view.coffee:235

TypeError: args.split is not a function
    at file:///C:/Users/ekaluc/.atom/packages/script/lib/script-options-view.coffee:88:14
    at ScriptOptionsView.module.exports.ScriptOptionsView.splitArgs (file:///C:/Users/ekaluc/.atom/packages/script/lib/script-options-view.coffee:88:14)
    at ScriptOptionsView.module.exports.ScriptOptionsView.getOptions (file:///C:/Users/ekaluc/.atom/packages/script/lib/script-options-view.coffee:100:15)
    at ScriptOptionsView.module.exports.ScriptOptionsView.saveProfile (file:///C:/Users/ekaluc/.atom/packages/script/lib/script-options-view.coffee:113:16)
    at HTMLButtonElement.<anonymous> (C:\Users\ekaluc\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\ekaluc\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\ekaluc\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -0:13.4.0 script:run-options (atom-text-editor.editor.is-focused)
     -0:09.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:09.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "exception-reporting",
      "atom-terminal-panel"
    ],
    "themes": [
      "tron-legacy-ui",
      "tron-legacy-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.14.1
autocomplete-js-import, v1.0.1
autocomplete-json, v5.0.3
autocomplete-modules, v1.5.1
autocomplete-paths, v1.0.2
autocomplete-project-paths, v2.2.0
browser-plus, v0.0.60
build, v0.64.0
build-gulp, v0.9.0
busy, v0.5.0
file-icons, v1.7.14
language-babel, v2.28.0
linter, v1.11.10
linter-eslint, v7.2.2
minimap, v4.24.6
minimap-pigments, v0.2.1
node-debugger, v1.7.0
open-recent, v5.0.0
pigments, v0.29.2
project-manager, v2.9.7
react, v0.15.0
script, v3.7.3
terminal-fusion, v2.1.4
tree-view-git-branch, v0.1.2
tree-view-git-status, v1.0.0
tron-legacy-syntax, v0.5.0
tron-legacy-ui, v0.6.0

# Dev
No dev packages
```

**Comment by nixel2007** [comment]
hi, @LightInjectedVenom!

what did you enter on script options window?

**Comment by LightInjectedVenom** [comment]
Hi,

Originally I entered ".\node_modules\babel-cli\bin\babel.js" {FILE_ACTIVE} --out-file out\{FILE_ACTIVE_NAME} for my options.

Then I removed " characters and it seems working now.
